services:
  - type: web
    name: stremio-titrari-ro
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /manifest.json
    autoDeploy: true
